### ISSUE TITLE
Publish a new release integrating the latest fixes

### ISSUE THREAD

**Issue by matteodelabre** [juruen/rmapi#63]
Hello,

The latest version, v0.0.4, suffers from issue #57 which unfortunately prevents using _rmapi_ for sending PDFs (the main use-case for me and, I suspect, many other users). Do you think it would be possible to publish a new version containing the latest commits?

Thank you!

**Comment by juruen** [comment]
@matteodelabre,  I just released a new version for MacOS.

**Comment by matteodelabre** [comment]
Thanks! Just a nitpick: it looks like you forgot to update the version string in https://github.com/juruen/rmapi/blob/edd77aadc9d4031fb93c4f9dbdd7e96e66859aed/version/version.go#L3

**Comment by juruen** [comment]
D'oh! I'll fix it this evening!

**Comment by juruen** [comment]
I fixed it a while ago.
